- name: Include default variables.
  include_vars:
    file: default.yml

- name: Specify MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{ mysql_root_password | quote }}' vtype='password'
  
- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ mysql_root_password | quote }}' vtype='password'
  become: true

- name: Install MySQL
  apt: pkg={{ item }} state=installed
  with_items:
    - mysql-server-5.7
    - python3-mysqldb
  update_cache: true
  
- name: Start the MySQL service
  action: service name=mysql state=started

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
